course 291883

user



// Update Row Status in a Course Enrollment
UPDATE COURSE_USERS
SET ROW_STATUS = 0
WHERE PK1 = (
SELECT
BB_BB60.COURSE_USERS.PK1
FROM
BB_BB60.COURSE_MAIN
INNER JOIN BB_BB60.COURSE_USERS ON BB_BB60.COURSE_USERS.CRSMAIN_PK1 = BB_BB60.COURSE_MAIN.PK1
INNER JOIN BB_BB60.USERS ON BB_BB60.COURSE_USERS.USERS_PK1 = BB_BB60.USERS.PK1
WHERE
BB_BB60.COURSE_MAIN.COURSE_ID = '<courseid>' AND
BB_BB60.USERS.USER_ID = '<userid>')


// Update Data Source Key for Enrollment in a Course
UPDATE DATA_SOURSE
SET ROW_STATUS = 2
WHERE PK1 = (SELECT
BB_BB60.DATA_SOURCE.PK1
FROM
BB_BB60.COURSE_MAIN
INNER JOIN BB_BB60.COURSE_USERS ON BB_BB60.COURSE_USERS.CRSMAIN_PK1 = BB_BB60.COURSE_MAIN.PK1
INNER JOIN BB_BB60.USERS ON BB_BB60.COURSE_USERS.USERS_PK1 = BB_BB60.USERS.PK1
INNER JOIN BB_BB60.DATA_SOURCE ON BB_BB60.COURSE_USERS.DATA_SRC_PK1 = BB_BB60.DATA_SOURCE.PK1
WHERE
BB_BB60.COURSE_MAIN.COURSE_ID = '<courseid>' AND
BB_BB60.USERS.USER_ID = '<userid>')